export const COLOR_PRESETS = [
  { name: "レッド",       value: "#EF4444" },
  { name: "ローズ",       value: "#F43F5E" },
  { name: "ピンク",       value: "#EC4899" },
  { name: "オレンジ",     value: "#F97316" },
  { name: "アンバー",     value: "#F59E0B" },
  { name: "イエロー",     value: "#EAB308" },
  { name: "ライム",       value: "#84CC16" },
  { name: "グリーン",     value: "#22C55E" },
  { name: "エメラルド",   value: "#10B981" },
  { name: "ティール",     value: "#14B8A6" },
  { name: "スカイ",       value: "#0EA5E9" },
  { name: "ブルー",       value: "#3B82F6" },
  { name: "インディゴ",   value: "#6366F1" },
  { name: "バイオレット", value: "#8B5CF6" },
  { name: "スレート",     value: "#64748B" },
  { name: "ストーン",     value: "#78716C" },
] as const;
